# HyperZoneLogin Entry Configuration - Example
# 这是一个示例配置文件，位于 example 文件夹中的配置不会被加载
# 复制此文件到 entry 文件夹（非 example 子文件夹）中并修改即可使用

# 此验证服务的 ID(无论大小写，到数据库会变成小写)，用于识别验证服务的唯一标识
id=Example
# 验证服务的别称，用于一些指令结果或其他用途的内容显示
name=Unnamed
# Yggdrasil 类型账号验证服务配置（当 serviceType 为 Yggdrasil 时有效）
yggdrasil {
    # Yggdrasil hasJoined 验证 URL
    url=""
    # 验证请求超时时间（毫秒）
    timeout=10000
    # 网络错误时的重试次数
    retry=0
    # 重试请求延迟（毫秒）
    retry-delay=0
    # 代理设置
    proxy {
        # 设置代理类型
        #             DIRECT - 直接连接、或没有代理
        #             HTTP - 表示高级协议(如HTTP或FTP)的代理
        #             SOCKS - 表示一个SOCKS (V4或V5)代理
        type=DIRECT
        # 代理服务器地址
        hostname="127.0.0.1"
        # 代理服务器端口
        port=1080
        # 代理鉴权用户名，留空则不进行鉴权
        username=""
        # 代理鉴权密码
        password=""
    }
}
